name: Beth Powell
favicon: null
layout_spectrum: 0.24201
typography_spectrum: 0.8058196639176458
title: Beth Powell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181310'
    - '#d5dad6'
    - '#3d3f3a'
    - '#595e58'
    - '#888d87'
  brandStrength: 0.9283554484136403
  lightness: 0.2770998605992645
  saturation: 0.36135959811508656
  rhythmicContrast: 0.37255988479591906
purpose: []
